### ISSUE TITLE
Support option to allow longer email addresses

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/address#1]
Hi,

Atm we use Joi 14 which uses isEmail to validate email addresses.
We use it like this: `Joi.string().email({ errorLevel: 68 })`.
As you can see we use the errorLevel to make the validation more relaxed, mainly for long email addresses.
Now the upgrade to a newer Joi version replaced isEmail with this module leaving us with no 'out of the box' option to migrate our email validation without breaking it.
I understand that this module tries to validate to spec as much as possible for our use case this strictness is just a bit too much (sadly :P).
The spec also states `4.5.3.1.  Size Limits and Minimums [...] To the maximum extent possible, implementation techniques that impose no limits on the length of these objects should be used.`
Would you consider an option to allow longer addresses and then exposing said option through Joi.email()?
I think it is mostly around this line https://github.com/hapijs/address/blob/master/lib/index.js#L98
If you want I can submit a PR for this.

**Comment by AdriVanHoudt** [comment]
@hueniverse friendly ping to get your opinion on this, would love to not have jump several major joi versions when 16 comes out :P

**Comment by hueniverse** [comment]
Closed by bc728f7677b9395e4d335b8b721dda3545409c8f

**Comment by AdriVanHoudt** [comment]
Thanks for this!
