### ISSUE TITLE
Export errors codes to allow translation

### ISSUE THREAD

**Issue by nkint** [hapijs/address#13]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Free support 
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.11.1
* *module version*: latest
* *environment* (e.g. node, browser, native): browser
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: Typescript 3.6.2

#### What problem are you trying to solve?

Hi, thanks for the template and the code of conduct - very inspirational words. Hope everything will be ok with this issue.

I'd like to use this `address` module: it is very exhaustive and I love the detailed feedback it gives back in case of error.

But I also need to translate error codes so I would like to have a list of all errors used and / or error codes. In my case have a translation/error-codes is mandatory and can compromise to use or not this library.

#### Do you have a new or modified API suggestion to solve the problem?

I'm here to discuss what is the best way to do it (if this can be a good idea for the maintainer) and hopefully find the time to have a mini pull-request.

One idea can be:

```js

const errorsByCode = {
    BE_STRING: 'Invalid input: email must be a string',
	BE_NON_EMPTY_STRING: 'Address must be a non-empty string',
    // ....
};

module.exports = {
	errorsByCode,
    domain: {
        // ....
    },
    email: {
        // ....       
    }
};

// use the error-codes in the rest of the source code
```

What do you think?

**Comment by hueniverse** [comment]
I'm open to it. The above looks like a good start. Feel free to submit a PR.
