### ISSUE TITLE
Incorrect validation

### ISSUE THREAD

**Issue by hueniverse** [hapijs/address#31]
- %-encoding is not actually verified to be correct in URIs
- HTTP URIs are not restricted per URI spec (should only allow `pathAbEmpty` in `hierPart`
- The domain in URIs is not validated (allows `http://example.com%2F')

Continued from https://github.com/hapijs/joi/issues/2360

**Comment by kanongil** [comment]
Fully-qualified hostnames (that end with a `.`), eg. `hapi.dev.` are handled as invalid (DOMAIN_EMPTY_SEGMENT).

**Comment by Marsup** [comment]
I think https://github.com/sideway/joi/issues/2685 also fits this issue. The punycode conversion decodes the %2e in this case.

**Comment by hueniverse** [comment]
Decided to be conservative:
- allow fully qualified domains only with flag `allowFullyQualified`
- prevent punycode from converting %-encoded values in domain
- prevent HTTP uris from having an empty domain
