### ISSUE TITLE
build-int tlds list vanished during typescript update

### ISSUE THREAD

**Issue by cherviakovtaskworld** [hapijs/address#46]
#### Context

* *node version*:  18.17.1
* *module version*: 5.1.1

#### What are you trying to achieve or the steps to reproduce ?

This module is very confusing. We used older version 4.1.0 of @hapi/address for build-in tlds list. Now that we make upgrade to the latest version 5.1.1 this tlds list is just gone! There no mention about it, aside of in [here](https://github.com/hapijs/address/issues/41) but without any reference to commit or PR. It just states
```
Remove built-in TLDS list support (moved to new @sideway/tlds module)
```
but such package not exists in npm! After some digging I finally found tlds list was removed in this [commit](https://github.com/hapijs/address/commit/0574ec8a280d08a8002e9763016a097f86c05d83)

Also I noticed that in npm present @sideways/address 5.0.0 It looks like joi have some fight with hapi, your own business, but please do update documentation properly and explain where things going, why and which are latest and correst modules, and in old and deprecated ones state that they are deprecated, it is a mess now!

**Comment by kanongil** [comment]
The module has moved between orgs.

The 5.x breaking changes can be found here: https://github.com/hapijs/address/milestone/20?closed=1.

You can find the new @hapi/tlds module here: https://github.com/hapijs/tlds

**Comment by cherviakovtaskworld** [comment]
Thanks for prompt asnwer @kanongil
