### ISSUE TITLE
Revert Url hack

### ISSUE THREAD

**Issue by hueniverse** [hapijs/address#6]
Reverting #4 as it increases bundle size by 12K. Basically, the node Url shim it pretty big and includes punycode anyways so this saves nothing for now.

**Comment by kanongil** [comment]
You can avoid the node `Url` dependency if you require only node v10+. Then the `URL` class will be available in a global. `URL` itself is [pretty widely supported](https://caniuse.com/#feat=url).

**Comment by kanongil** [comment]
This can also be handled in web pack. Eg. add this to the config:

```js
    resolve: {
        alias: {
            url: Path.join(__dirname, 'src/url.js'),
        }
    }
```

and this `src/url.js` file:

```js
exports.URL = URL;
```

**Comment by hueniverse** [comment]
Cool. I'll try it later before I close joi v16.
